services:
  mysql-service:
    image: mysql/mysql-server:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    env_file: .env

  web-app:
    image: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      mysql-service:
        condition: service_healthy
